server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_gateway
    driver-class-name: org.postgresql.Driver
    username: currency_gateway
    password: currency_gateway_pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update